M48
; DRILL file {KiCad 9.0.6} date 2025-11-30T22:11:01+1000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-30T22:11:01+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X193.003Y-71.003
X197.853Y-71.003
T2
X192.703Y-67.973
X198.153Y-67.973
M30
